apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    run: pod
spec:
  containers:
    - image: {{.Image}}
      name: {{.ContainerName}}
      ports:
        - containerPort: 80